<a href="https://colab.research.google.com/github/jamesgunadi24/Case-Study-01-Data-Mining---EDA---Ganjil-2022-Kelompok-L/blob/main/jasidoaosdj.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# Importing Modules untuk Notebook ini
import warnings; warnings.simplefilter('ignore')
try:
    import google.colab; IN_COLAB = True
    !pip install umap-learn
    !wget https://raw.githubusercontent.com/taudata-indonesia/eLearning/master/tau_unsup.py
except:
    IN_COLAB = False
    print("Running the code locally, please make sure all the python module versions agree with colab environment and all data/assets downloaded")
import umap, numpy as np, tau_unsup as tau, matplotlib.pyplot as plt, pandas as pd, seaborn as sns
from sklearn import cluster, datasets
from sklearn.metrics import silhouette_score as siluet
from sklearn.metrics.cluster import homogeneity_score as purity
from sklearn.metrics import normalized_mutual_info_score as NMI 

sns.set(style="ticks", color_codes=True)
random_state = 99 #ini buat untuk random_state dan ini penting banget buat kmeans

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Collecting umap-learn
  Downloading umap-learn-0.5.3.tar.gz (88 kB)
     |████████████████████████████████| 88 kB 4.9 MB/s
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.7/dist-packages (from umap-learn) (1.21.6)
Requirement already satisfied: scikit-learn>=0.22 in /usr/local/lib/python3.7/dist-packages (from umap-learn) (1.0.2)
Requirement already satisfied: scipy>=1.0 in /usr/local/lib/python3.7/dist-packages (from umap-learn) (1.7.3)
Requirement already satisfied: numba>=0.49 in /usr/local/lib/python3.7/dist-packages (from umap-learn) (0.56.3)
Collecting pynndescent>=0.5
  Downloading pynndescent-0.5.7.tar.gz (1.1 MB)
     |████████████████████████████████| 1.1 MB 52.7 MB/s
Requirement already satisfied: tqdm in /usr/local/lib/python3.7/dist-packages (from umap-learn) (4.64.1)
Requirement already satisfied: setuptools in /usr/local/lib/python3.7/dist-packages (from numba>=0.49->umap-learn) (57.4.0)
Requirement already satisfied: importlib-metadata in /usr/local/lib/python3.7/dist-packages (from numba>=0.49->umap-learn) (4.13.0)
Requirement already satisfied: llvmlite<0.40,>=0.39.0dev0 in /usr/local/lib/python3.7/dist-packages (from numba>=0.49->umap-learn) (0.39.1)
Requirement already satisfied: joblib>=0.11 in /usr/local/lib/python3.7/dist-packages (from pynndescent>=0.5->umap-learn) (1.2.0)
Requirement already satisfied: threadpoolctl>=2.0.0 in /usr/local/lib/python3.7/dist-packages (from scikit-learn>=0.22->umap-learn) (3.1.0)
Requirement already satisfied: typing-extensions>=3.6.4 in /usr/local/lib/python3.7/dist-packages (from importlib-metadata->numba>=0.49->umap-learn) (4.1.1)
Requirement already satisfied: zipp>=0.5 in /usr/local/lib/python3.7/dist-packages (from importlib-metadata->numba>=0.49->umap-learn) (3.9.0)
Building wheels for collected packages: umap-learn, pynndescent
  Building wheel for umap-learn (setup.py) ... done
  Created wheel for umap-learn: filename=umap_learn-0.5.3-py3-none-any.whl size=82829 sha256=e375f7cb737fd37fc67bf15ac82ed1ab2cdb7ca0cd8281a07b3b623947cd5c7d
  Stored in directory: /root/.cache/pip/wheels/b3/52/a5/1fd9e3e76a7ab34f134c07469cd6f16e27ef3a37aeff1fe821
  Building wheel for pynndescent (setup.py) ... done
  Created wheel for pynndescent: filename=pynndescent-0.5.7-py3-none-any.whl size=54286 sha256=a949401575fdbdd2ed793d696de9db9e8283ac0c69706964d46dfedd79d6a365
  Stored in directory: /root/.cache/pip/wheels/7f/2a/f8/7bd5dcec71bd5c669f6f574db3113513696b98f3f9b51f496c
Successfully built umap-learn pynndescent
Installing collected packages: pynndescent, umap-learn
Successfully installed pynndescent-0.5.7 umap-learn-0.5.3
--2022-10-21 06:26:52--  https://raw.githubusercontent.com/taudata-indonesia/eLearning/master/tau_unsup.py
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.108.133, 185.199.109.133, 185.199.110.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.108.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 17387 (17K) [text/plain]
Saving to: ‘tau_unsup.py’

tau_unsup.py        100%[===================>]  16.98K  --.-KB/s    in 0s

2022-10-21 06:26:52 (77.1 MB/s) - ‘tau_unsup.py’ saved [17387/17387]

In [5]:
!mkdir data
url = 'https://raw.githubusercontent.com/YovelaYvone/MBA/main/datastudycase21okt.csv'
df = pd.read_csv(url,sep=';', index_col=0)
df

mkdir: cannot create directory ‘data’: File exists

,Tanggal,Konsumen,ID Produk,Nama Produk,Merek,Jumlah
ID Transaksi,,,,,,
1,01/07/22 00.00,Mr. A,1,Roti,Sri Roti,2
1,01/07/22 00.00,Mr. A,2,Air Minum,Aquos,1
1,01/07/22 00.00,Mr. A,11,Mie Instan,Indomi,2
1,01/07/22 00.00,Mr. A,12,Mie Instan,Mi Sedap,1
2,01/07/22 00.00,Mr. B,2,Air Minum,Aquos,1
2,01/07/22 00.00,Mr. B,6,Snack,Chiki,2
2,01/07/22 00.00,Mr. B,3,Roti,Prambanan,1
2,01/07/22 00.00,Mr. B,5,Shampoo,Clean,1
3,02/07/22 00.00,Mr. C,4,Sabun,Lifboy,1
3,02/07/22 00.00,Mr. C,5,Shampoo,Clean,1
3,02/07/22 00.00,Mr. C,9,Rokok,Malioboro,1
4,02/07/22 00.00,Mr. B,1,Roti,Sri Roti,2
4,02/07/22 00.00,Mr. B,10,Air Minum,Sprit,2
4,02/07/22 00.00,Mr. B,8,Snack,Citata,3
4,02/07/22 00.00,Mr. B,7,Sabun,Luks,1
4,02/07/22 00.00,Mr. B,12,Mie Instan,Mi Sedap,2
5,03/07/22 00.00,Mr. A,6,Snack,Chiki,1
5,03/07/22 00.00,Mr. A,10,Air Minum,Sprit,2
6,03/07/22 00.00,Mr. D,11,Mie Instan,Indomi,2
6,03/07/22 00.00,Mr. D,4,Sabun,Lifboy,1
6,03/07/22 00.00,Mr. D,5,Shampoo,Clean,1
7,04/07/22 00.00,Mr. Z,10,Air Minum,Sprit,1
7,04/07/22 00.00,Mr. Z,9,Rokok,Malioboro,1
8,04/07/22 00.00,Mr. B,6,Snack,Chiki,1
8,04/07/22 00.00,Mr. B,7,Sabun,Luks,1
8,04/07/22 00.00,Mr. B,5,Shampoo,Clean,1
8,04/07/22 00.00,Mr. B,11,Mie Instan,Indomi,3
9,05/07/22 00.00,Mr. X,1,Roti,Sri Roti,2
9,05/07/22 00.00,Mr. X,2,Air Minum,Aquos,1
9,05/07/22 00.00,Mr. X,4,Sabun,Lifboy,1
9,05/07/22 00.00,Mr. X,6,Snack,Chiki,2
9,05/07/22 00.00,Mr. X,9,Rokok,Malioboro,1
9,05/07/22 00.00,Mr. X,11,Mie Instan,Indomi,2
10,05/07/22 00.00,Mr. T,3,Roti,Prambanan,1
10,05/07/22 00.00,Mr. T,10,Air Minum,Sprit,2
10,05/07/22 00.00,Mr. T,6,Snack,Chiki,2
11,06/07/22 00.00,Mr. P,3,Roti,Prambanan,2
11,06/07/22 00.00,Mr. P,9,Rokok,Malioboro,1
12,06/07/22 00.00,Mr. G,4,Sabun,Lifboy,2
12,06/07/22 00.00,Mr. G,5,Shampoo,Clean,1
12,06/07/22 00.00,Mr. G,12,Mie Instan,Mi Sedap,2
12,06/07/22 00.00,Mr. G,11,Mie Instan,Indomi,1
13,07/07/22 00.00,Mr. X,1,Roti,Sri Roti,1
13,07/07/22 00.00,Mr. X,8,Snack,Citata,2
13,07/07/22 00.00,Mr. X,10,Air Minum,Sprit,1
14,07/07/22 00.00,Mr.Y,7,Sabun,Luks,2
14,07/07/22 00.00,Mr.Y,5,Shampoo,Clean,2
14,07/07/22 00.00,Mr.Y,6,Snack,Chiki,1
15,08/07/22 00.00,Mr. F,9,Rokok,Malioboro,1
16,02/08/22 00.00,Mr. J,2,Air Minum,Aquos,2
17,05/09/22 00.00,Mr. X,1,Roti,Sri Roti,2
17,05/09/22 00.00,Mr. X,2,Air Minum,Aquos,1
17,05/09/22 00.00,Mr. X,4,Sabun,Lifboy,1
17,05/09/22 00.00,Mr. X,6,Snack,Chiki,2
18,02/10/22 00.00,Mr. B,1,Roti,Sri Roti,2
18,02/10/22 00.00,Mr. B,10,Air Minum,Sprit,2

In [6]:
df.dtypes

Tanggal        object
Konsumen       object
ID Produk       int64
Nama Produk    object
Merek          object
Jumlah          int64
dtype: object

In [7]:
df['Tanggal'] = pd.to_datetime(df['Tanggal'])

ParserError: ignored